### PR TITLE
WIP: Rails 4.3 → Rails 6, Ruby 2.5 → 3.2.3 Upgrade 

### PR DESCRIPTION
**Pull request by kigster**
This is a work in progress.

I got it to a point where the Rails 6.0 boots the console, and you can run rake tasks, migrations, and specs. 

However, specs are not yet all passing.

There is still plenty to do, but it's getting there.

### CODE REVIEW

**Review by mike-matera — COMMENTED** [review]
It's not possible to review this PR because there are too many changes. I'm happy to help if I  can but I see these issues as blocking useful review:

1. Virtually every Ruby file has changed and the changes seem to have been made by robot. These bury consequential changes in an ocean of unimportant ones. 
2. There is a large volume of `vim` files here. It's generally preferred to let developers keep their environments for themselves and not push settings into a source code repo. 

@kigster ... If you're taking over the maintenance of this repo, that's great and I want to support you. We don't really need the PR process for development that has a single programmer. So I'm fine if you want to merge this and move forward.

**Comment by kigster** [comment]
@mike-matera this PR is not ready for a review to begin with.

Secondly, having spoken to several people who upgrade rails for a living, there is no easy incremental way of doing it for our app unfortunately.

Luckily we have a great test coverage here and I plan to increase it before making this ready for a review, as well as placing this branch on a review app.

While I appreciate your concern, let's cross that bridge when it's ready.

**Comment by kigster** [comment]
I added @fnf-org/fnf-engineeres to the reviewer list to make interested folks aware this work is happening to avoid any effort duplication. I've coordinated it with @beingmattlevy.

The description clearly says it's not yet ready. Sorry if this caused any confusion.

**Comment by kigster** [comment]
The point about vim folder is valid. I was also thinking it does not belong here.

**Pull request closed without merging**
